# Generated by Django 4.1.7 on 2023-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbr_name', models.CharField(max_length=100)),
                ('mbr_img', models.ImageField(upload_to='pics')),
                ('mbr_dsc', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='dsc',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
